elasticsearch:
  
  host: "x.x.x.x"
  port: 9240
  index:
    name:
      
      drivers: "gateway_default_analytics"

  pipeline:
    name: "driver-enrichment-pipeline"
    path: "pipeline/driver-enrichment.json"
  policy:
    name: "enrich-statistics-policy"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://x.x.x.x:3306/database
    username: root
    password: password

# todo_1
not-decrypted-services:
  - signatureX
  - generateTokenJWT
  - signatureServiceSnap